server:
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-password: ENC(ZhwAAvI0E4+27aMceE1yX6S4xGNQ8hv7)
    key-store-type: PKCS12
spring:
  application:
    name: server
  data:
    mongodb:
        uri: ENC(JU21mv6qBbOG/PnK+4k32l0V4LIG8q/12s06PcsJeKqgatCt/xgG5QmU7r0CS6pQg80Phwuq6Wd/dNmaodAybdymjY7PV9zxsj3iALsnk8+DbNW5FCN54Q==)
  ai:
    openai:
      api-key: ENC(Q3Uz+kDQOa6uqGIIOPKQir6wuluFtPJh//eW64znzhcEgLQicPcQEbhvzSwIVnYuJJTj0UbT+113Py5wLQJEUsR9X1xViczbxSgwcOZ/2QiSlvZnVVrRs8gKdro6zUhQcVDOacXRa0POlqxgmvXl+u9OMKASTKbiLd0LInJIr2eReoxCpwlAM8xEkFmMg5fImKZahb1VbUwdQXpTHuCqDFOIkoFn9uQN1uVIJy/hDx4=)
      chat:
        options:
          model: gpt-4o
          temperature: 0.6
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(xPjELBLjOj95Wwe3SELd9A==)
    password: ENC(MlhBMa4p/8AyE+JrRf2VmurvINVU+c2V)
    url: ENC(PvrdFqoZIXCEQ2cHxPY14dJDWacC4qKiV08pKtjbYIKXBsS5K+91jcn4vQkeQeb8)
  jpa:
    hibernate:
      ddl-auto: update
  jwt:
    secret: 5wlXHtmN2l/i74J7a/A7mxiR5xYNmiRLJa6kfwgBg74biLDj1wT62BNoltMxw9sEDMzb/CEB4l0=
  jackson:
    time-zone: Asia/Seoul
  logging:
    level:
      org.springframework.data.mongodb.core.MongoTemplate: DEBUG
