server:
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-password: ENC(ZhwAAvI0E4+27aMceE1yX6S4xGNQ8hv7)
    key-store-type: PKCS12
spring:
  naver:
    cloud:
      url: ENC(V60O8eTNILfEkz6CQXGUo39Ts3ketkXbhG8m3z5A8+ocwQf3xu8L8omgeDmNDt+57y2hD7uV4DgEr3XeLuG18FajJ93pfZE/m5XIy3+sj5j2rQjYNc9VTyCYRvVIjjiDmc4+ancKTyYdfGKeUkWAxKRZ4wtlouIWKOYp5AYXgRo=)
      secret: ENC(xA03xBoT+28mrbdQW4sUZL+5HgtlIALzgXpOUEbng2ByQagV//PNUxMGBhLCpTEJ)
  application:
    name: server
  data:
    mongodb:
        user: ENC(rb5R56qnCmrtE+SZHSxITA==)
        password: ENC(/trrcpFOSrkiXU+aCDuqM2RBeIrv9sXW)
        uri: ENC(qHVHRsYCKJfzhuGKzJo6t0zd7m4rhRoY1jh4HDvu9LyQFvjjrmvFukBZ1jJJUKWx)
      
  ai:
    openai:
      api-key: ENC(Q3Uz+kDQOa6uqGIIOPKQir6wuluFtPJh//eW64znzhcEgLQicPcQEbhvzSwIVnYuJJTj0UbT+113Py5wLQJEUsR9X1xViczbxSgwcOZ/2QiSlvZnVVrRs8gKdro6zUhQcVDOacXRa0POlqxgmvXl+u9OMKASTKbiLd0LInJIr2eReoxCpwlAM8xEkFmMg5fImKZahb1VbUwdQXpTHuCqDFOIkoFn9uQN1uVIJy/hDx4=)
      chat:
        options:
          model: gpt-4o
          temperature: 0.6
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(xPjELBLjOj95Wwe3SELd9A==)
    password: ENC(MlhBMa4p/8AyE+JrRf2VmurvINVU+c2V)
    url: ENC(PvrdFqoZIXCEQ2cHxPY14dJDWacC4qKiV08pKtjbYIKXBsS5K+91jcn4vQkeQeb8)
  jpa:
    hibernate:
      ddl-auto: update
  jwt:
    secret: 5wlXHtmN2l/i74J7a/A7mxiR5xYNmiRLJa6kfwgBg74biLDj1wT62BNoltMxw9sEDMzb/CEB4l0=
  jackson:
    time-zone: Asia/Seoul
  logging:
    level:
      org.springframework.data.mongodb.core.MongoTemplate: DEBUG
