version: "3.8"

services:
  spring-boot:
    container_name: spring-boot
    build: ../../server
    environment:
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - my_network

networks:
  my_network:
