version: "3.8"

services:
  spring-boot:
    container_name: spring-boot
    build: ../../server
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my_network

networks:
  my_network:
