version: "3.8"

services:
  mysql:
    image: mysql:8.0.40
    environment:
      MYSQL_DATABASE: lucky
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
